import solve from './index';

describe('Day6', () => {
    test('Easy input 1', () => {
        const input = `....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...
`;
        const result = solve(input);
        expect(result.part1).toBe(41);
        expect(result.part2).toBe(6);
    });
});
